"""Compile the Qwen3-VL vision transformer MBLT to MXQ (encoder, benchmark-best 4B config).

This run applies 16-bit activations on the merger/deepstack fc2 layers and a
head_out_ch_rotation that CONSUMES the SpinR1 rotation matrix produced by the
decoder MXQ compilation at:
    ./spinWeight/Qwen3-VL-4B-Instruct_text_model/R1/global_rotation.pth
Run this AFTER mxq_compile_language.py.
"""

import os
from argparse import ArgumentParser

import torch
from qbcompiler import mxq_compile
from qbcompiler.configs import (
    BitConfig,
    CalibrationConfig,
    EquivalentTransformationConfig,
    LlmConfig,
    ResourceManagementConfig,
)

TARGET_DEVICES = ["regulus-ra", "aries-rb", "regulus-rb"]

# The SpinR1 matrix is generated by the decoder MXQ compilation. Its directory is
# derived from the decoder MXQ save basename (Qwen3-VL-4B-Instruct_text_model).
ROTATION_MATRIX_PATH = "./spinWeight/Qwen3-VL-4B-Instruct_text_model/R1/global_rotation.pth"


def get_device_inference_scheme(target_device):
    # REGULUS only supports the single scheme; ARIES supports all schemes in one model.
    if "regulus" in target_device:
        return "single"
    elif "aries" in target_device:
        return "all"
    raise ValueError(f"{target_device} not supported in current qbcompiler version")


if __name__ == "__main__":
    parser = ArgumentParser(description="Compile Qwen3-VL vision transformer MBLT to MXQ")
    parser.add_argument(
        "--target-device",
        type=str,
        required=True,
        choices=TARGET_DEVICES,
        help="Target NPU (e.g. aries-rb, regulus-rb)",
    )
    args = parser.parse_args()

    mblt_path = "mblt/Qwen3-VL-4B-Instruct_vision_transformer.mblt"
    save_path = "mxq/Qwen3-VL-4B-Instruct_vision_transformer.mxq"
    calib_data_path = "calibration_data/vision/npy_files.txt"
    device = "gpu" if torch.cuda.is_available() else "cpu"

    # Ensure output directory exists
    output_dir = os.path.dirname(os.path.abspath(save_path))
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    calibration_config = CalibrationConfig(output=0, mode=1)

    bit_config = BitConfig(
        layer_overrides=BitConfig.LayerOverrides(
            activation_16bits=[
                "model_merger_linear_fc2",
                "model_deepstack_merger_list_0_linear_fc2",
                "model_deepstack_merger_list_1_linear_fc2",
                "model_deepstack_merger_list_2_linear_fc2",
            ],
        ),
    )

    resource_management_config = ResourceManagementConfig(
        weight_dtype="float32",
        use_gpu_only_for_calibration=True,
        weight_memory=ResourceManagementConfig.WeightMemory(method=1),
    )

    llm_config = LlmConfig(
        apply=True,
        attributes=LlmConfig.Attributes(
            calibration=LlmConfig.Attributes.Calibration(use_full_seq_length=True),
        ),
    )

    equivalent_transformation_config = EquivalentTransformationConfig(
        qk=EquivalentTransformationConfig.Qk(apply=True),
        ud=EquivalentTransformationConfig.Ud(apply=True),
        vo=EquivalentTransformationConfig.Vo(apply=True),
        head_out_ch_rotation=EquivalentTransformationConfig.HeadOutChRotation(
            apply=True,
            matrix_path=ROTATION_MATRIX_PATH,
        ),
        spin_r1=EquivalentTransformationConfig.SpinR1(apply=False),
        spin_r2=EquivalentTransformationConfig.SpinR2(apply=True),
        optimize_ffn=EquivalentTransformationConfig.OptimizeFfn(apply=True),
    )

    mxq_compile(
        mblt_path,
        target_device=args.target_device,
        save_path=save_path,
        calib_data_path=calib_data_path,
        device=device,
        inference_scheme=get_device_inference_scheme(args.target_device),
        calibration_config=calibration_config,
        bit_config=bit_config,
        resource_management_config=resource_management_config,
        llm_config=llm_config,
        equivalent_transformation_config=equivalent_transformation_config,
    )
